# Generated by Django 5.2.4 on 2025-08-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('url', models.CharField(max_length=200, verbose_name='Havola')),
                ('column', models.CharField(choices=[('courses', 'Kurslar'), ('company', 'Kompaniya'), ('support', 'Yordam'), ('contact', 'Aloqa')], default='company', max_length=20, verbose_name='Ustun')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Yangi oynada ochish')),
            ],
            options={
                'verbose_name': 'Footer link',
                'verbose_name_plural': 'Footer linklar',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_logo', models.ImageField(blank=True, upload_to='footer/')),
                ('footer_description', models.TextField(blank=True, verbose_name='Footer tavsifi')),
                ('copyright_text', models.CharField(default="© 2024 Tibbiy Ta'lim Platformasi. Barcha huquqlar himoyalangan.", max_length=200, verbose_name='Copyright matni')),
                ('show_courses_column', models.BooleanField(default=True, verbose_name="Kurslar ustunini ko'rsatish")),
                ('show_company_column', models.BooleanField(default=True, verbose_name="Kompaniya ustunini ko'rsatish")),
                ('show_support_column', models.BooleanField(default=True, verbose_name="Yordam ustunini ko'rsatish")),
                ('show_contact_column', models.BooleanField(default=True, verbose_name="Aloqa ustunini ko'rsatish")),
                ('newsletter_title', models.CharField(blank=True, default="Yangiliklardan xabardor bo'ling", max_length=100)),
                ('newsletter_description', models.TextField(blank=True, verbose_name='Newsletter tavsifi')),
                ('newsletter_active', models.BooleanField(default=True, verbose_name='Newsletter faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer sozlamalari',
                'verbose_name_plural': 'Footer sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_phone', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_search', models.BooleanField(default=True)),
                ('show_language_switcher', models.BooleanField(default=False)),
                ('announcement_text', models.CharField(blank=True, max_length=200, verbose_name="E'lon matni")),
                ('announcement_url', models.URLField(blank=True, verbose_name="E'lon linki")),
                ('announcement_active', models.BooleanField(default=False, verbose_name="E'lonni ko'rsatish")),
                ('header_transparent', models.BooleanField(default=False, verbose_name='Shaffof header')),
                ('header_sticky', models.BooleanField(default=True, verbose_name='Yapishqoq header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header sozlamalari',
                'verbose_name_plural': 'Header sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter obunachi',
                'verbose_name_plural': 'Newsletter obunachilar',
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Sahifa nomi (home, courses, lessons, etc.)', max_length=100, unique=True, verbose_name='Sahifa nomi')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta sarlavha')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta tavsif')),
                ('meta_keywords', models.TextField(blank=True, verbose_name="Meta kalit so'zlar")),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=100, verbose_name='OG sarlavha')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='OG tavsif')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='OG rasm')),
                ('twitter_title', models.CharField(blank=True, max_length=100, verbose_name='Twitter sarlavha')),
                ('twitter_description', models.CharField(blank=True, max_length=200, verbose_name='Twitter tavsif')),
                ('twitter_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='Twitter rasm')),
            ],
            options={
                'verbose_name': 'SEO sahifa',
                'verbose_name_plural': 'SEO sahifalar',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="Tibbiy Ta'lim Platformasi", max_length=100)),
                ('site_description', models.TextField(default="Professional tibbiy ta'lim onlayn platformasi")),
                ('site_keywords', models.TextField(help_text="SEO uchun kalit so'zlar (vergul bilan ajrating)")),
                ('site_logo', models.ImageField(blank=True, upload_to='site/')),
                ('site_favicon', models.ImageField(blank=True, upload_to='site/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50)),
                ('meta_author', models.CharField(blank=True, max_length=100)),
                ('site_maintenance', models.BooleanField(default=False, help_text='Sayt texnik ishlar rejimida')),
                ('registration_open', models.BooleanField(default=True, help_text="Ro'yxatdan o'tishga ruxsat")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('show_in_header', models.BooleanField(default=True, verbose_name="Header da ko'rsatish")),
                ('show_in_footer', models.BooleanField(default=True, verbose_name="Footer da ko'rsatish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoqlar',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Lavozim')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Kompaniya')),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Avatar')),
                ('content', models.TextField(verbose_name='Sharh matni')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 yulduz'), (2, '2 yulduz'), (3, '3 yulduz'), (4, '4 yulduz'), (5, '5 yulduz')], default=5, verbose_name='Baho')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy sharhlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavbarMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('url', models.CharField(help_text='URL yoki URL nomi', max_length=200, verbose_name='Havola')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, verbose_name='Ikonka')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navbarmenu', verbose_name='Ota-element')),
            ],
            options={
                'verbose_name': 'Navbar menu',
                'verbose_name_plural': 'Navbar menular',
                'ordering': ['order'],
            },
        ),
    ]
